In [9]:
%%time
%%sql
select @@version;

Running query in 'mysql+mysqlconnector://ivan:***@localhost:3306'

1 rows affected.

CPU times: user 3.71 ms, sys: 913 us, total: 4.62 ms
Wall time: 6.05 ms

In [10]:
%%sql
use airportdb;
call sys.heatwave_load(JSON_ARRAY("airportdb"), null);

Running query in 'mysql+mysqlconnector://ivan:***@localhost:3306'

6 rows affected.

   INITIALIZING HEATWAVE AUTO PARALLEL LOAD
0                             Version: 4.52
1
2                         Load Mode: normal
3  Load Policy: disable_unsupported_columns
4                       Output Mode: normal
5

In [11]:
%%time
# %sql ALTER TABLE weatherdata secondary_load;
%sql select @mytime := sysdate(6);  
%time myoutput = %sql select /*+ SET_VAR(use_secondary_engine=ON) */ "ON" status, log_date, count(*) from weatherdata where log_date > DATE '2005-01-01' group by log_date order by log_date;
display(myoutput.DataFrame().tail(10))
myoutput = %sql select timediff(sysdate(6), @mytime);
display(myoutput)
%sql select @mytime := sysdate(6);
%time myoutput = %sql select /*+ SET_VAR(use_secondary_engine=OFF) */"OFF" status, log_date, count(*) from weatherdata where log_date > DATE '2005-01-01' group by log_date order by log_date;
display(myoutput.DataFrame().tail(10))
myoutput = %sql select timediff(sysdate(6), @mytime);
display(myoutput)

Running query in 'mysql+mysqlconnector://ivan:***@localhost:3306'

1 rows affected.

Running query in 'mysql+mysqlconnector://ivan:***@localhost:3306'

4015 rows affected.

CPU times: user 7.82 ms, sys: 1.22 ms, total: 9.04 ms
Wall time: 65.9 ms

     status                  log_date  count(*)
4005     ON  2015-12-21T00:00:00.000Z      1152
4006     ON  2015-12-22T00:00:00.000Z      1152
4007     ON  2015-12-23T00:00:00.000Z      1152
4008     ON  2015-12-24T00:00:00.000Z      1152
4009     ON  2015-12-25T00:00:00.000Z      1152
4010     ON  2015-12-26T00:00:00.000Z      1152
4011     ON  2015-12-27T00:00:00.000Z      1152
4012     ON  2015-12-28T00:00:00.000Z      1152
4013     ON  2015-12-29T00:00:00.000Z      1152
4014     ON  2015-12-30T00:00:00.000Z      1152

Running query in 'mysql+mysqlconnector://ivan:***@localhost:3306'

1 rows affected.

  timediff(sysdate(6), @mytime)
0               00:00:00.077511

Running query in 'mysql+mysqlconnector://ivan:***@localhost:3306'

1 rows affected.

Running query in 'mysql+mysqlconnector://ivan:***@localhost:3306'

4015 rows affected.

CPU times: user 8.35 ms, sys: 0 ns, total: 8.35 ms
Wall time: 467 ms

     status                  log_date  count(*)
4005    OFF  2015-12-21T00:00:00.000Z      1152
4006    OFF  2015-12-22T00:00:00.000Z      1152
4007    OFF  2015-12-23T00:00:00.000Z      1152
4008    OFF  2015-12-24T00:00:00.000Z      1152
4009    OFF  2015-12-25T00:00:00.000Z      1152
4010    OFF  2015-12-26T00:00:00.000Z      1152
4011    OFF  2015-12-27T00:00:00.000Z      1152
4012    OFF  2015-12-28T00:00:00.000Z      1152
4013    OFF  2015-12-29T00:00:00.000Z      1152
4014    OFF  2015-12-30T00:00:00.000Z      1152

Running query in 'mysql+mysqlconnector://ivan:***@localhost:3306'

1 rows affected.

  timediff(sysdate(6), @mytime)
0               00:00:00.477916

CPU times: user 47.8 ms, sys: 1.49 ms, total: 49.3 ms
Wall time: 569 ms

In [12]:
%%sql
explain select count(*) from weatherdata where log_date > DATE '2005-01-01'group by log_date order by log_date;

Running query in 'mysql+mysqlconnector://ivan:***@localhost:3306'

1 rows affected.

                                             EXPLAIN
0  -> Sort: weatherdata.log_date  (cost=31122..12...

In [13]:

%%sql
set autocommit=true;
EXPLAIN SELECT
airline.airlinename,
AVG(datediff(departure,birthdate)/365.25) as avg_age,
count(*) as nb_people
FROM
    booking, flight, airline, passengerdetails
WHERE
    booking.flight_id=flight.flight_id AND
    airline.airline_id=flight.airline_id AND
    booking.passenger_id=passengerdetails.passenger_id AND
    country IN ("SWITZERLAND", "FRANCE", "ITALY")
GROUP BY
    airline.airlinename
ORDER BY
    airline.airlinename, avg_age
LIMIT 10;

Running query in 'mysql+mysqlconnector://ivan:***@localhost:3306'

1 rows affected.

                                             EXPLAIN
0  -> Sort: airline.airlinename, limit input to 1...

In [14]:

%%sql
set autocommit=false;
EXPLAIN SELECT
airline.airlinename,
AVG(datediff(departure,birthdate)/365.25) as avg_age,
count(*) as nb_people
FROM
    booking, flight, airline, passengerdetails
WHERE
    booking.flight_id=flight.flight_id AND
    airline.airline_id=flight.airline_id AND
    booking.passenger_id=passengerdetails.passenger_id AND
    country IN ("SWITZERLAND", "FRANCE", "ITALY")
GROUP BY
    airline.airlinename
ORDER BY
    airline.airlinename, avg_age
LIMIT 10;

Running query in 'mysql+mysqlconnector://ivan:***@localhost:3306'

1 rows affected.

                                             EXPLAIN
0  -> Sort: airline.airlinename, limit input to 1...

In [15]:
%%time
%%sql
set autocommit=true;
SELECT /*+ SET_VAR(use_secondary_engine=FORCED) */
airline.airlinename,
AVG(datediff(departure,birthdate)/365.25) as avg_age,
count(*) as nb_people
FROM
    booking, flight, airline, passengerdetails
WHERE
    booking.flight_id=flight.flight_id AND
    airline.airline_id=flight.airline_id AND
    booking.passenger_id=passengerdetails.passenger_id AND
    country IN ("SWITZERLAND", "FRANCE", "ITALY")
GROUP BY
    airline.airlinename
ORDER BY
    airline.airlinename, avg_age
LIMIT 10;

Running query in 'mysql+mysqlconnector://ivan:***@localhost:3306'

10 rows affected.

CPU times: user 10.1 ms, sys: 990 us, total: 11.1 ms
Wall time: 112 ms

In [16]:
%%time
%%sql
set autocommit=true;
SELECT /*+ SET_VAR(use_secondary_engine=OFF) */
airline.airlinename,
AVG(datediff(departure,birthdate)/365.25) as avg_age,
count(*) as nb_people
FROM
    booking, flight, airline, passengerdetails
WHERE
    booking.flight_id=flight.flight_id AND
    airline.airline_id=flight.airline_id AND
    booking.passenger_id=passengerdetails.passenger_id AND
    country IN ("SWITZERLAND", "FRANCE", "ITALY")
GROUP BY
    airline.airlinename
ORDER BY
    airline.airlinename, avg_age
LIMIT 10;

Running query in 'mysql+mysqlconnector://ivan:***@localhost:3306'

10 rows affected.

CPU times: user 16.2 ms, sys: 1.26 ms, total: 17.4 ms
Wall time: 10.1 s