In [1]:
# Machine Learning
# https://apexapps.oracle.com/pls/apex/r/dbpm/livelabs/run-workshop?p210_wid=3306

%reload_ext sql
a=%sql show databases;
display(a)
%sql select database();

15 rows affected.

                     Database
0             ML_SCHEMA_admin
1              ML_SCHEMA_ivan
2           ML_SCHEMA_mieszko
3                   airportdb
4                  creditcard
5  fraud_detection_creditcard
6          information_schema
7                      khaled
8                       mysql
9                 mysql_audit

Running query in 'mysql+mysqlconnector://ivan:***@localhost:3306'

1 rows affected.

  database()
0       None

In [3]:
%sql create database if not exists irisdb;
%sql use irisdb;
%sql show databases;
%sql show tables;

Running query in 'mysql+mysqlconnector://ivan:***@localhost:3306'

1 rows affected.

Running query in 'mysql+mysqlconnector://ivan:***@localhost:3306'

Running query in 'mysql+mysqlconnector://ivan:***@localhost:3306'

16 rows affected.

Running query in 'mysql+mysqlconnector://ivan:***@localhost:3306'

Empty DataFrame
Columns: [Tables_in_irisdb]
Index: []

In [6]:
%%sql
   drop table if exists iris_train;
   
   CREATE TABLE if not exists `iris_train` (
       my_row_id bigint not null auto_increment primary key invisible ,
      `sepal length` float DEFAULT NULL,
      `sepal width` float DEFAULT NULL,
      `petal length` float DEFAULT NULL,
      `petal width` float DEFAULT NULL,
      `class` varchar(16) DEFAULT NULL
    );
    
    truncate table iris_train;
    
    INSERT INTO iris_train VALUES(6.4,2.8,5.6,2.2,'Iris-virginica');
    INSERT INTO iris_train VALUES(5.0,2.3,3.3,1.0,'Iris-setosa');
    INSERT INTO iris_train VALUES(4.9,2.5,4.5,1.7,'Iris-virginica');
    INSERT INTO iris_train VALUES(4.9,3.1,1.5,0.1,'Iris-versicolor');
    INSERT INTO iris_train VALUES(5.7,3.8,1.7,0.3,'Iris-versicolor');
    INSERT INTO iris_train VALUES(4.4,3.2,1.3,0.2,'Iris-versicolor');
    INSERT INTO iris_train VALUES(5.4,3.4,1.5,0.4,'Iris-versicolor');
    INSERT INTO iris_train VALUES(6.9,3.1,5.1,2.3,'Iris-virginica');
    INSERT INTO iris_train VALUES(6.7,3.1,4.4,1.4,'Iris-setosa');
    INSERT INTO iris_train VALUES(5.1,3.7,1.5,0.4,'Iris-versicolor');
    INSERT INTO iris_train VALUES(5.2,2.7,3.9,1.4,'Iris-setosa');
    INSERT INTO iris_train VALUES(6.9,3.1,4.9,1.5,'Iris-setosa');
    INSERT INTO iris_train VALUES(5.8,4.0,1.2,0.2,'Iris-versicolor');
    INSERT INTO iris_train VALUES(5.4,3.9,1.7,0.4,'Iris-versicolor');
    INSERT INTO iris_train VALUES(7.7,3.8,6.7,2.2,'Iris-virginica');
    INSERT INTO iris_train VALUES(6.3,3.3,4.7,1.6,'Iris-setosa');
    INSERT INTO iris_train VALUES(6.8,3.2,5.9,2.3,'Iris-virginica');
    INSERT INTO iris_train VALUES(7.6,3.0,6.6,2.1,'Iris-virginica');
    INSERT INTO iris_train VALUES(6.4,3.2,5.3,2.3,'Iris-virginica');
    INSERT INTO iris_train VALUES(5.7,4.4,1.5,0.4,'Iris-versicolor');
    INSERT INTO iris_train VALUES(6.7,3.3,5.7,2.1,'Iris-virginica');
    INSERT INTO iris_train VALUES(6.4,2.8,5.6,2.1,'Iris-virginica');
    INSERT INTO iris_train VALUES(5.4,3.9,1.3,0.4,'Iris-versicolor');
    INSERT INTO iris_train VALUES(6.1,2.6,5.6,1.4,'Iris-virginica');
    INSERT INTO iris_train VALUES(7.2,3.0,5.8,1.6,'Iris-virginica');
    INSERT INTO iris_train VALUES(5.2,3.5,1.5,0.2,'Iris-versicolor');
    INSERT INTO iris_train VALUES(5.8,2.6,4.0,1.2,'Iris-setosa');
    INSERT INTO iris_train VALUES(5.9,3.0,5.1,1.8,'Iris-virginica');
    INSERT INTO iris_train VALUES(5.4,3.0,4.5,1.5,'Iris-setosa');
    INSERT INTO iris_train VALUES(6.7,3.0,5.0,1.7,'Iris-setosa');
    INSERT INTO iris_train VALUES(6.3,2.3,4.4,1.3,'Iris-setosa');
    INSERT INTO iris_train VALUES(5.1,2.5,3.0,1.1,'Iris-setosa');
    INSERT INTO iris_train VALUES(6.4,3.2,4.5,1.5,'Iris-setosa');
    INSERT INTO iris_train VALUES(6.8,3.0,5.5,2.1,'Iris-virginica');
    INSERT INTO iris_train VALUES(6.2,2.8,4.8,1.8,'Iris-virginica');
    INSERT INTO iris_train VALUES(6.9,3.2,5.7,2.3,'Iris-virginica');
    INSERT INTO iris_train VALUES(6.5,3.2,5.1,2.0,'Iris-virginica');
    INSERT INTO iris_train VALUES(5.8,2.8,5.1,2.4,'Iris-virginica');
    INSERT INTO iris_train VALUES(5.1,3.8,1.5,0.3,'Iris-versicolor');
    INSERT INTO iris_train VALUES(4.8,3.0,1.4,0.3,'Iris-versicolor');
    INSERT INTO iris_train VALUES(7.9,3.8,6.4,2.0,'Iris-virginica');
    INSERT INTO iris_train VALUES(5.8,2.7,5.1,1.9,'Iris-virginica');
    INSERT INTO iris_train VALUES(6.7,3.0,5.2,2.3,'Iris-virginica');
    INSERT INTO iris_train VALUES(5.1,3.8,1.9,0.4,'Iris-versicolor');
    INSERT INTO iris_train VALUES(4.7,3.2,1.6,0.2,'Iris-versicolor');
    INSERT INTO iris_train VALUES(6.0,2.2,5.0,1.5,'Iris-virginica');
    INSERT INTO iris_train VALUES(4.8,3.4,1.6,0.2,'Iris-versicolor');
    INSERT INTO iris_train VALUES(7.7,2.6,6.9,2.3,'Iris-virginica');
    INSERT INTO iris_train VALUES(4.6,3.6,1.0,0.2,'Iris-versicolor');
    INSERT INTO iris_train VALUES(7.2,3.2,6.0,1.8,'Iris-virginica');
    INSERT INTO iris_train VALUES(5.0,3.3,1.4,0.2,'Iris-versicolor');
    INSERT INTO iris_train VALUES(6.6,3.0,4.4,1.4,'Iris-setosa');
    INSERT INTO iris_train VALUES(6.1,2.8,4.0,1.3,'Iris-setosa');
    INSERT INTO iris_train VALUES(5.0,3.2,1.2,0.2,'Iris-versicolor');
    INSERT INTO iris_train VALUES(7.0,3.2,4.7,1.4,'Iris-setosa');
    INSERT INTO iris_train VALUES(6.0,3.0,4.8,1.8,'Iris-virginica');
    INSERT INTO iris_train VALUES(7.4,2.8,6.1,1.9,'Iris-virginica');
    INSERT INTO iris_train VALUES(5.8,2.7,5.1,1.9,'Iris-virginica');
    INSERT INTO iris_train VALUES(6.2,3.4,5.4,2.3,'Iris-virginica');
    INSERT INTO iris_train VALUES(5.0,2.0,3.5,1.0,'Iris-setosa');
    INSERT INTO iris_train VALUES(5.6,2.5,3.9,1.1,'Iris-setosa');
    INSERT INTO iris_train VALUES(6.7,3.1,5.6,2.4,'Iris-virginica');
    INSERT INTO iris_train VALUES(6.3,2.5,5.0,1.9,'Iris-virginica');
    INSERT INTO iris_train VALUES(6.4,3.1,5.5,1.8,'Iris-virginica');
    INSERT INTO iris_train VALUES(6.2,2.2,4.5,1.5,'Iris-setosa');
    INSERT INTO iris_train VALUES(7.3,2.9,6.3,1.8,'Iris-virginica');
    INSERT INTO iris_train VALUES(4.4,3.0,1.3,0.2,'Iris-versicolor');
    INSERT INTO iris_train VALUES(7.2,3.6,6.1,2.5,'Iris-virginica');
    INSERT INTO iris_train VALUES(6.5,3.0,5.5,1.8,'Iris-virginica');
    INSERT INTO iris_train VALUES(5.0,3.4,1.5,0.2,'Iris-versicolor');
    INSERT INTO iris_train VALUES(4.7,3.2,1.3,0.2,'Iris-versicolor');
    INSERT INTO iris_train VALUES(6.6,2.9,4.6,1.3,'Iris-setosa');
    INSERT INTO iris_train VALUES(5.5,3.5,1.3,0.2,'Iris-versicolor');
    INSERT INTO iris_train VALUES(7.7,3.0,6.1,2.3,'Iris-virginica');
    INSERT INTO iris_train VALUES(6.1,3.0,4.9,1.8,'Iris-virginica');
    INSERT INTO iris_train VALUES(4.9,3.1,1.5,0.1,'Iris-versicolor');
    INSERT INTO iris_train VALUES(5.5,2.4,3.8,1.1,'Iris-setosa');
    INSERT INTO iris_train VALUES(5.7,2.9,4.2,1.3,'Iris-setosa');
    INSERT INTO iris_train VALUES(6.0,2.9,4.5,1.5,'Iris-setosa');
    INSERT INTO iris_train VALUES(6.4,2.7,5.3,1.9,'Iris-virginica');
    INSERT INTO iris_train VALUES(5.4,3.7,1.5,0.2,'Iris-versicolor');
    INSERT INTO iris_train VALUES(6.1,2.9,4.7,1.4,'Iris-setosa');
    INSERT INTO iris_train VALUES(6.5,2.8,4.6,1.5,'Iris-setosa');
    INSERT INTO iris_train VALUES(5.6,2.7,4.2,1.3,'Iris-setosa');
    INSERT INTO iris_train VALUES(6.3,3.4,5.6,2.4,'Iris-virginica');
    INSERT INTO iris_train VALUES(4.9,3.1,1.5,0.1,'Iris-versicolor');
    INSERT INTO iris_train VALUES(6.8,2.8,4.8,1.4,'Iris-setosa');
    INSERT INTO iris_train VALUES(5.7,2.8,4.5,1.3,'Iris-setosa');
    INSERT INTO iris_train VALUES(6.0,2.7,5.1,1.6,'Iris-setosa');
    INSERT INTO iris_train VALUES(5.0,3.5,1.3,0.3,'Iris-versicolor');
    INSERT INTO iris_train VALUES(6.5,3.0,5.2,2.0,'Iris-virginica');
    INSERT INTO iris_train VALUES(6.1,2.8,4.7,1.2,'Iris-setosa');
    INSERT INTO iris_train VALUES(5.1,3.5,1.4,0.3,'Iris-versicolor');
    INSERT INTO iris_train VALUES(4.6,3.1,1.5,0.2,'Iris-versicolor');
    INSERT INTO iris_train VALUES(6.5,3.0,5.8,2.2,'Iris-virginica');
    INSERT INTO iris_train VALUES(4.6,3.4,1.4,0.3,'Iris-versicolor');
    INSERT INTO iris_train VALUES(4.6,3.2,1.4,0.2,'Iris-versicolor');
    INSERT INTO iris_train VALUES(7.7,2.8,6.7,2.0,'Iris-virginica');
    INSERT INTO iris_train VALUES(5.9,3.2,4.8,1.8,'Iris-setosa');
    INSERT INTO iris_train VALUES(5.1,3.8,1.6,0.2,'Iris-versicolor');
    INSERT INTO iris_train VALUES(4.9,3.0,1.4,0.2,'Iris-versicolor');
    INSERT INTO iris_train VALUES(4.9,2.4,3.3,1.0,'Iris-setosa');
    INSERT INTO iris_train VALUES(4.5,2.3,1.3,0.3,'Iris-versicolor');
    INSERT INTO iris_train VALUES(5.8,2.7,4.1,1.0,'Iris-setosa');
    INSERT INTO iris_train VALUES(5.0,3.4,1.6,0.4,'Iris-versicolor');
    INSERT INTO iris_train VALUES(5.2,3.4,1.4,0.2,'Iris-versicolor');
    INSERT INTO iris_train VALUES(5.3,3.7,1.5,0.2,'Iris-versicolor');
    INSERT INTO iris_train VALUES(5.0,3.6,1.4,0.2,'Iris-versicolor');
    INSERT INTO iris_train VALUES(5.6,2.9,3.6,1.3,'Iris-setosa');
    INSERT INTO iris_train VALUES(4.8,3.1,1.6,0.2,'Iris-versicolor');
    INSERT INTO iris_train VALUES(6.3,2.7,4.9,1.8,'Iris-virginica');
    INSERT INTO iris_train VALUES(5.7,2.8,4.1,1.3,'Iris-setosa');
    INSERT INTO iris_train VALUES(5.0,3.0,1.6,0.2,'Iris-versicolor');
    INSERT INTO iris_train VALUES(6.3,3.3,6.0,2.5,'Iris-virginica');
    INSERT INTO iris_train VALUES(5.0,3.5,1.6,0.6,'Iris-versicolor');
    INSERT INTO iris_train VALUES(5.5,2.6,4.4,1.2,'Iris-setosa');
    INSERT INTO iris_train VALUES(5.7,3.0,4.2,1.2,'Iris-setosa');
    INSERT INTO iris_train VALUES(4.4,2.9,1.4,0.2,'Iris-versicolor');
    INSERT INTO iris_train VALUES(4.8,3.0,1.4,0.1,'Iris-versicolor');
    INSERT INTO iris_train VALUES(5.5,2.4,3.7,1.0,'Iris-setosa');
    
    DROP TABLE if exists iris_test;
    CREATE TABLE  `iris_test` LIKE `iris_train`;
    
    INSERT INTO iris_test VALUES(5.9,3.0,4.2,1.5,'Iris-setosa');
    INSERT INTO iris_test VALUES(6.9,3.1,5.4,2.1,'Iris-virginica');
    INSERT INTO iris_test VALUES(5.1,3.3,1.7,0.5,'Iris-versicolor');
    INSERT INTO iris_test VALUES(6.0,3.4,4.5,1.6,'Iris-setosa');
    INSERT INTO iris_test VALUES(5.5,2.5,4.0,1.3,'Iris-setosa');
    INSERT INTO iris_test VALUES(6.2,2.9,4.3,1.3,'Iris-setosa');
    INSERT INTO iris_test VALUES(5.5,4.2,1.4,0.2,'Iris-versicolor');
    INSERT INTO iris_test VALUES(6.3,2.8,5.1,1.5,'Iris-virginica');
    INSERT INTO iris_test VALUES(5.6,3.0,4.1,1.3,'Iris-setosa');
    INSERT INTO iris_test VALUES(6.7,2.5,5.8,1.8,'Iris-virginica');
    INSERT INTO iris_test VALUES(7.1,3.0,5.9,2.1,'Iris-virginica');
    INSERT INTO iris_test VALUES(4.3,3.0,1.1,0.1,'Iris-versicolor');
    INSERT INTO iris_test VALUES(5.6,2.8,4.9,2.0,'Iris-virginica');
    INSERT INTO iris_test VALUES(5.5,2.3,4.0,1.3,'Iris-setosa');
    INSERT INTO iris_test VALUES(6.0,2.2,4.0,1.0,'Iris-setosa');
    INSERT INTO iris_test VALUES(5.1,3.5,1.4,0.2,'Iris-versicolor');
    INSERT INTO iris_test VALUES(5.7,2.6,3.5,1.0,'Iris-setosa');
    INSERT INTO iris_test VALUES(4.8,3.4,1.9,0.2,'Iris-versicolor');
    INSERT INTO iris_test VALUES(5.1,3.4,1.5,0.2,'Iris-versicolor');
    INSERT INTO iris_test VALUES(5.7,2.5,5.0,2.0,'Iris-virginica');
    INSERT INTO iris_test VALUES(5.4,3.4,1.7,0.2,'Iris-versicolor');
    INSERT INTO iris_test VALUES(5.6,3.0,4.5,1.5,'Iris-setosa');
    INSERT INTO iris_test VALUES(6.3,2.9,5.6,1.8,'Iris-virginica');
    INSERT INTO iris_test VALUES(6.3,2.5,4.9,1.5,'Iris-setosa');
    INSERT INTO iris_test VALUES(5.8,2.7,3.9,1.2,'Iris-setosa');
    INSERT INTO iris_test VALUES(6.1,3.0,4.6,1.4,'Iris-setosa');
    INSERT INTO iris_test VALUES(5.2,4.1,1.5,0.1,'Iris-versicolor');
    INSERT INTO iris_test VALUES(6.7,3.1,4.7,1.5,'Iris-setosa');
    INSERT INTO iris_test VALUES(6.7,3.3,5.7,2.5,'Iris-virginica');
    INSERT INTO iris_test VALUES(6.4,2.9,4.3,1.3,'Iris-setosa');
    
    drop table if exists `iris_validate`;
    CREATE TABLE `iris_validate` LIKE `iris_test`;
    
    INSERT INTO `iris_validate` SELECT * FROM `iris_test`;

Running query in 'mysql+mysqlconnector://ivan:***@localhost:3306'

1 rows affected.

1 rows affected.

1 rows affected.

1 rows affected.

1 rows affected.

1 rows affected.

1 rows affected.

1 rows affected.

1 rows affected.

1 rows affected.

1 rows affected.

1 rows affected.

1 rows affected.

1 rows affected.

1 rows affected.

1 rows affected.

1 rows affected.

1 rows affected.

1 rows affected.

1 rows affected.

1 rows affected.

1 rows affected.

1 rows affected.

1 rows affected.

1 rows affected.

1 rows affected.

1 rows affected.

1 rows affected.

1 rows affected.

1 rows affected.

1 rows affected.

1 rows affected.

1 rows affected.

1 rows affected.

1 rows affected.

1 rows affected.

1 rows affected.

1 rows affected.

1 rows affected.

1 rows affected.

1 rows affected.

1 rows affected.

1 rows affected.

1 rows affected.

1 rows affected.

1 rows affected.

1 rows affected.

1 rows affected.

1 rows affected.

1 rows affected.

1 rows affected.

1 rows affected.

1 rows affected.

1 rows affected.

1 rows affected.

1 rows affected.

1 rows affected.

1 rows affected.

1 rows affected.

1 rows affected.

1 rows affected.

1 rows affected.

1 rows affected.

1 rows affected.

1 rows affected.

1 rows affected.

1 rows affected.

1 rows affected.

1 rows affected.

1 rows affected.

1 rows affected.

1 rows affected.

1 rows affected.

1 rows affected.

1 rows affected.

1 rows affected.

1 rows affected.

1 rows affected.

1 rows affected.

1 rows affected.

1 rows affected.

1 rows affected.

1 rows affected.

1 rows affected.

1 rows affected.

1 rows affected.

1 rows affected.

1 rows affected.

1 rows affected.

1 rows affected.

1 rows affected.

1 rows affected.

1 rows affected.

1 rows affected.

1 rows affected.

1 rows affected.

1 rows affected.

1 rows affected.

1 rows affected.

1 rows affected.

1 rows affected.

1 rows affected.

1 rows affected.

1 rows affected.

1 rows affected.

1 rows affected.

1 rows affected.

1 rows affected.

1 rows affected.

1 rows affected.

1 rows affected.

1 rows affected.

1 rows affected.

1 rows affected.

1 rows affected.

1 rows affected.

1 rows affected.

1 rows affected.

1 rows affected.

1 rows affected.

1 rows affected.

1 rows affected.

1 rows affected.

1 rows affected.

1 rows affected.

1 rows affected.

1 rows affected.

1 rows affected.

1 rows affected.

1 rows affected.

1 rows affected.

1 rows affected.

1 rows affected.

1 rows affected.

1 rows affected.

1 rows affected.

1 rows affected.

1 rows affected.

1 rows affected.

1 rows affected.

1 rows affected.

1 rows affected.

1 rows affected.

1 rows affected.

1 rows affected.

1 rows affected.

1 rows affected.

1 rows affected.

1 rows affected.

1 rows affected.

30 rows affected.

++
||
++
++

In [7]:
%%sql 
select @iris_model:='iris_model';
DELETE FROM ML_SCHEMA_ivan.MODEL_CATALOG
WHERE model_handle COLLATE utf8mb4_0900_ai_ci = @iris_model;

Running query in 'mysql+mysqlconnector://ivan:***@localhost:3306'

1 rows affected.

++
||
++
++

In [8]:
%%time
%sql select @iris_model:='iris_model';
%sql select @bf:=sysdate(6);
%sql CALL sys.ML_TRAIN('irisdb.iris_train', 'class',JSON_OBJECT('task', 'classification', 'exclude_column_list', JSON_ARRAY('my_row_id')), @iris_model);
%sql select 'completed',now(), timediff(sysdate(6), @bf);

Running query in 'mysql+mysqlconnector://ivan:***@localhost:3306'

1 rows affected.

Running query in 'mysql+mysqlconnector://ivan:***@localhost:3306'

1 rows affected.

Running query in 'mysql+mysqlconnector://ivan:***@localhost:3306'

Running query in 'mysql+mysqlconnector://ivan:***@localhost:3306'

1 rows affected.

CPU times: user 41.5 ms, sys: 6.7 ms, total: 48.2 ms
Wall time: 47.7 s

In [9]:
%%time
%sql select @iris_model:='iris_model';
mymodel = %sql SELECT * FROM ML_SCHEMA_ivan.MODEL_CATALOG where model_handle = 'iris_model';
display(mymodel)
%sql CALL sys.ML_MODEL_LOAD(@iris_model, NULL);

Running query in 'mysql+mysqlconnector://ivan:***@localhost:3306'

1 rows affected.

Running query in 'mysql+mysqlconnector://ivan:***@localhost:3306'

1 rows affected.

+----------+--------------+----------------------+----------------+--------------+-------------+-----------------+--------------------+-------------------+----------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------+---------------+-------------------+-------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| model_id | model_handle |      model_type      |      task      | model_object | model_owner | build_timestamp | target_column_name |  train_table_name |                          column_names                          |                                                     model_explanation                                                      | last_accessed | model_object_size | notes |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       model_metadata                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
+----------+--------------+----------------------+----------------+--------------+-------------+-----------------+--------------------+-------------------+----------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------+---------------+-------------------+-------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|    1     |  iris_model  | ExtraTreesClassifier | classification |     None     |     ivan    |    1769116940   |       class        | irisdb.iris_train | ['sepal length', 'sepal width', 'petal length', 'petal width'] | {"permutation_importance": {"petal width": 0.2301, "sepal width": 0.0056, "petal length": 0.2192, "sepal length": 0.0056}} |      None     |       404186      |  None | {"task": "classification", "notes": null, "chunks": 1, "format": "HWMLv2.0", "n_rows": 120, "status": "Ready", "options": {"task": "classification", "model_explainer": "permutation_importance", "exclude_column_list": ["my_row_id"], "prediction_explainer": "permutation_importance"}, "n_columns": 4, "column_names": ["sepal length", "sepal width", "petal length", "petal width"], "contamination": null, "model_quality": "high", "training_time": 31.373252868652344, "algorithm_name": "ExtraTreesClassifier", "training_score": -0.1097036823630333, "build_timestamp": 1769116940, "hyperparameters": {"criterion": "entropy", "max_features": 0.25, "n_estimators": 5, "min_samples_leaf": 0.008333333333333333, "min_samples_split": 0.0012598333333333333}, "n_selected_rows": 96, "training_params": {"recommend": "ratings", "force_use_X": false, "recommend_k": 3, "remove_seen": true, "ranking_topk": 10, "lsa_components": 100, "ranking_threshold": 1, "feedback_threshold": 1}, "train_table_name": "irisdb.iris_train", "model_explanation": {"permutation_importance": {"petal width": 0.2301, "sepal width": 0.0056, "petal length": 0.2192, "sepal length": 0.0056}}, "n_selected_columns": 4, "target_column_name": "class", "optimization_metric": "neg_log_loss", "selected_column_names": ["petal length", "petal width", "sepal length", "sepal width"], "training_drift_metric": {"mean": 0.2779, "variance": 0.1398}} |
+----------+--------------+----------------------+----------------+--------------+-------------+-----------------+--------------------+-------------------+----------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------+---------------+-------------------+-------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

Running query in 'mysql+mysqlconnector://ivan:***@localhost:3306'

CPU times: user 59.8 ms, sys: 5.95 ms, total: 65.7 ms
Wall time: 1.04 s

In [10]:
%%time
%sql select @iris_model:='iris_model';
%sql SET @row_input = JSON_OBJECT( "sepal length", 7.3, "sepal width", 2.9, "petal length", 6.3, "petal width", 1.8);
myoutput = %sql SELECT sys.ML_PREDICT_ROW(@row_input, @iris_model, NULL);
display(myoutput)
myoutput = %sql SELECT JSON_PRETTY(sys.ML_PREDICT_ROW(@row_input, @iris_model, NULL)); 
display(myoutput)

Running query in 'mysql+mysqlconnector://ivan:***@localhost:3306'

1 rows affected.

Running query in 'mysql+mysqlconnector://ivan:***@localhost:3306'

Running query in 'mysql+mysqlconnector://ivan:***@localhost:3306'

1 rows affected.

   sys.ML_PREDICT_ROW(@row_input, @iris_model, NULL)
0  {"Prediction": "Iris-virginica", "ml_results":...

Running query in 'mysql+mysqlconnector://ivan:***@localhost:3306'

1 rows affected.

  JSON_PRETTY(sys.ML_PREDICT_ROW(@row_input, @iris_model, NULL))
0  {\n  "Prediction": "Iris-virginica",\n  "ml_re...

CPU times: user 22 ms, sys: 0 ns, total: 22 ms
Wall time: 801 ms

In [11]:
%%sql
SELECT JSON_PRETTY(sys.ML_PREDICT_ROW(@row_input, @iris_model, NULL));

Running query in 'mysql+mysqlconnector://ivan:***@localhost:3306'

1 rows affected.

  JSON_PRETTY(sys.ML_PREDICT_ROW(@row_input, @iris_model, NULL))
0  {\n  "Prediction": "Iris-virginica",\n  "ml_re...

In [12]:
%%sql
SELECT JSON_PRETTY(sys.ML_EXPLAIN_ROW(@row_input, @iris_model, JSON_OBJECT('prediction_explainer', 'permutation_importance')));

Running query in 'mysql+mysqlconnector://ivan:***@localhost:3306'

1 rows affected.

  JSON_PRETTY(sys.ML_EXPLAIN_ROW(@row_input, @iris_model, JSON_OBJECT('prediction_explainer', 'permutation_importance')))
0  {\n  "Notes": "petal length (6.3) had the larg...