In [1]:
%load_ext sql

In [4]:
x = %sql show databases;
display(x)
x = %sql use demodata;

Running query in 'mysql+mysqlconnector://ivan:***@localhost:3306'

18 rows affected.

                     Database
0             ML_SCHEMA_admin
1              ML_SCHEMA_ivan
2           ML_SCHEMA_mieszko
3                   airportdb
4                  creditcard
5                    demodata
6                   financedb
7  fraud_detection_creditcard
8          information_schema
9                      irisdb

Running query in 'mysql+mysqlconnector://ivan:***@localhost:3306'

In [5]:
%%sql
use demodata;
show tables;

Running query in 'mysql+mysqlconnector://ivan:***@localhost:3306'

2 rows affected.

  Tables_in_demodata
0            mytrain
1         train_data

In [6]:
%%sql
show create table train_data;

Running query in 'mysql+mysqlconnector://ivan:***@localhost:3306'

1 rows affected.

        Table                                       Create Table
0  train_data  CREATE TABLE `train_data` (\n  `my_row_id` big...

In [7]:
x = %sql select count(*) from train_data ;
display(x)
x = %sql drop table if exists mytrain;
x = %sql create table mytrain like train_data;
x = %sql insert into mytrain select * from train_data limit 10000;

Running query in 'mysql+mysqlconnector://ivan:***@localhost:3306'

1 rows affected.

   count(*)
0    345573

Running query in 'mysql+mysqlconnector://ivan:***@localhost:3306'

Running query in 'mysql+mysqlconnector://ivan:***@localhost:3306'

Running query in 'mysql+mysqlconnector://ivan:***@localhost:3306'

10000 rows affected.

In [8]:

import pandas as pd

# sample data
rs = %sql select * from mytrain limit 10;
df1 = pd.DataFrame(rs)
display(df1)

Running query in 'mysql+mysqlconnector://ivan:***@localhost:3306'

10 rows affected.

                     company_name  ... change_reason
0        Vivos Therapeutics, Inc.  ...            \r
1             VSI Providers, PLLC  ...            \r
2               GRANITE PEAK CORP  ...            \r
3     Dragon Industrial Wrap, LLC  ...            \r
4   Kristi's test company 2/24/21  ...            \r
5                  Cobb South 298  ...            \r
6    Diamond S Mobile Welding LLC  ...            \r
7  T&J Industries Development and  ...            \r
8                Divine Power LLC  ...            \r
9                          Vac2Go  ...            \r

[10 rows x 23 columns]

In [9]:
%%sql
set @modelid = 'demodata.model01';
DELETE FROM ML_SCHEMA_ivan.MODEL_CATALOG where model_handle COLLATE utf8mb4_0900_ai_ci = @modelid;

Running query in 'mysql+mysqlconnector://ivan:***@localhost:3306'

1 rows affected.

++
||
++
++

In [10]:
%%sql
-- The contamination value must be greater than 0 and less than 0.5. The default value is 0.01.
call sys.ML_TRAIN("demodata.mytrain", null, JSON_OBJECT('task', 'anomaly_detection', 'contamination', 0.01, 
                                                      'exclude_column_list', JSON_ARRAY('my_row_id')), @modelid);

Running query in 'mysql+mysqlconnector://ivan:***@localhost:3306'

++
||
++
++

In [11]:
%%sql
SELECT JSON_EXTRACT(model_metadata, '$.contamination') 
          FROM ML_SCHEMA_ivan.MODEL_CATALOG 
          WHERE model_handle = @modelid;

Running query in 'mysql+mysqlconnector://ivan:***@localhost:3306'

1 rows affected.

   JSON_EXTRACT(model_metadata, '$.contamination')
0                                             0.01

In [21]:
%%sql

drop table mytest;
create table mytest like train_data;

 insert into mytest select train_data.* from train_data left join mytrain on (train_data.my_row_id = mytrain.my_row_id) where mytrain.my_row_id is null limit 10;

show tables;

Running query in 'mysql+mysqlconnector://ivan:***@localhost:3306'

10 rows affected.

3 rows affected.

  Tables_in_demodata
0             mytest
1            mytrain
2         train_data

In [22]:
%%sql


select * from mytest;

Running query in 'mysql+mysqlconnector://ivan:***@localhost:3306'

10 rows affected.

                     company_name  ... change_reason
0  Modern Mechanical Services LLC  ...            \r
1  Schaffhouser Electric Company,  ...            \r
2            Bandon Senior Living  ...            \r
3          Stellant Systems, Inc.  ...            \r
4         Concrete Profiles, Inc.  ...            \r
5                    Henry County  ...            \r
6                          Howden  ...            \r
7     Park Manor of The Woodlands  ...            \r
8              MKD Electric, Inc.  ...            \r
9         REYCON CONSTRUCTION INC  ...            \r

[10 rows x 23 columns]

In [25]:
%%sql
call sys.ML_MODEL_LOAD(@modelid, null);
drop table if exists demodata.myprediction;
call sys.ML_PREDICT_TABLE('demodata.mytest', @modelid, 'demodata.myprediction', JSON_OBJECT('threshold', 0.6));

Running query in 'mysql+mysqlconnector://ivan:***@localhost:3306'

++
||
++
++

In [24]:
%%sql
alter table demodata.mytest modify my_row_id bigint not null ;

Running query in 'mysql+mysqlconnector://ivan:***@localhost:3306'

10 rows affected.

++
||
++
++

In [26]:
%%sql
select * from demodata.myprediction;

Running query in 'mysql+mysqlconnector://ivan:***@localhost:3306'

10 rows affected.

   my_row_id  ...                                         ml_results
0          1  ...  {"predictions": {"is_anomaly": 0}, "probabilit...
1          2  ...  {"predictions": {"is_anomaly": 0}, "probabilit...
2          3  ...  {"predictions": {"is_anomaly": 0}, "probabilit...
3          4  ...  {"predictions": {"is_anomaly": 0}, "probabilit...
4          5  ...  {"predictions": {"is_anomaly": 0}, "probabilit...
5          6  ...  {"predictions": {"is_anomaly": 0}, "probabilit...
6          7  ...  {"predictions": {"is_anomaly": 0}, "probabilit...
7          8  ...  {"predictions": {"is_anomaly": 0}, "probabilit...
8          9  ...  {"predictions": {"is_anomaly": 0}, "probabilit...
9         10  ...  {"predictions": {"is_anomaly": 0}, "probabilit...

[10 rows x 25 columns]

In [27]:
%%sql
-- Note : this has to run external LLM
CALL sys.NL2ML("Given the table demodata.mytrain, what model task is good for training and prediction", @output);

Running query in 'mysql+mysqlconnector://ivan:***@localhost:3306'

++
||
++
++

In [28]:
%%sql
select json_pretty(@output);
  "text": "Based on the provided table schema for \"mytrain\" in the \"sysmax\" schema, 
  a suitable model task for training and prediction could be regression or classification
  , depending on the target variable.\n\nIf the goal is to predict a continuous value, 
  such as \"total_hours_worked\" or \"annual_average_employees\", 
  a regression task would be appropriate.\n\n
  If the goal is to predict a categorical value, 
  such as \"establishment_type\" or \"industry_description\", 
  a classification task would be suitable.\n\nHowever, 
  without more information about the specific problem you're trying to solve,
   it's difficult to provide a more specific recommendation. 
   \n\nAnother possibility is to use the table for anomaly detection, 
   to identify unusual patterns or outliers in the data, 
   such as companies with unusually high or low injury rates. 
   \n\nIt's also possible to use the table for forecasting, 
   to predict future values of certain columns, 
   such as \"total_deaths\" or \"total_dafw_cases\", 
   based on historical trends. \n\n
   More information about the problem you're trying to solve would be needed to 
   provide a more specific recommendation."

Running query in 'mysql+mysqlconnector://ivan:***@localhost:3306'

1 rows affected.

                                json_pretty(@output)
0  {\n  "text": "Based on the provided table sche...

In [44]:
%%sql
CALL sys.NL2ML("Given the table demodata.mytrain, what is best training if we want to predict the total no_injuries_illnesses", @output);

 * mysql+mysqlconnector://admin:***@143.47.226.231/mysql
0 rows affected.

[]

In [45]:
%%sql
select json_pretty(@output);

 * mysql+mysqlconnector://admin:***@143.47.226.231/mysql
1 rows affected.

[('{\n  "text": "**Data Preparation: **\\n\\n    To determine the best model training approach for predicting the total number of injuries and illnesses ... (2751 characters truncated) ...             \'exclude_column_list\', JSON_ARRAY(\'my_row_id\', \'created_timestamp\', \'change_reason\')), \\n                  @my_model);\\n```"\n}',)]