In [1]:
%load_ext sql
%config SqlMagic.displaylimit = None

The sql extension is already loaded. To reload it, use:
  %reload_ext sql

displaylimit: Value None will be treated as 0 (no limit)

In [2]:
x = %sql show databases;
display(x)
x = %sql use demodata;

18 rows affected.

                     Database
0             ML_SCHEMA_admin
1              ML_SCHEMA_ivan
2           ML_SCHEMA_mieszko
3                   airportdb
4                  creditcard
5                    demodata
6                   financedb
7  fraud_detection_creditcard
8          information_schema
9                      irisdb

Running query in 'mysql+mysqlconnector://ivan:***@localhost:3306'

In [3]:
%%sql
use demodata;
show tables;

show create table train_data;

Running query in 'mysql+mysqlconnector://ivan:***@localhost:3306'

5 rows affected.

1 rows affected.

        Table                                       Create Table
0  train_data  CREATE TABLE `train_data` (\n  `my_row_id` big...

In [29]:
x = %sql select count(*) from train_data ;
display(x)
x = %sql drop table if exists mytrain;
x = %sql create table mytrain like train_data;
x = %sql insert into mytrain select * from train_data limit 10000;

 * mysql+mysqlconnector://admin:***@143.47.226.231/mysql
1 rows affected.

[(345574,)]

 * mysql+mysqlconnector://admin:***@143.47.226.231/mysql
0 rows affected.
 * mysql+mysqlconnector://admin:***@143.47.226.231/mysql
0 rows affected.
 * mysql+mysqlconnector://admin:***@143.47.226.231/mysql
10000 rows affected.

In [8]:

import pandas as pd

# sample data
rs = %sql select * from mytrain limit 10;
df1 = pd.DataFrame(rs)
display(df1)

 * mysql+mysqlconnector://admin:***@143.47.226.231/mysql
10 rows affected.

,company_name,industry_description,annual_average_employees,total_hours_worked,no_injuries_illnesses,total_deaths,total_dafw_cases,total_djtr_cases,total_other_cases,total_dafw_days,...,total_respiratory_conditions,total_skin_disorders,total_hearing_loss,total_other_illnesses,establishment_id,establishment_type,size,year_filing_for,created_timestamp,change_reason
0,"Vivos Therapeutics, Inc.",DDSs' (doctors of dental surge,175,68331,1,0,1,0,0,3,...,0,0,0,0,797780,1,2,2022,1/1/2023,\r
1,"VSI Providers, PLLC",DDSs' (doctors of dental surge,4,5928,2,0,0,0,0,0,...,0,0,0,0,797800,1,1,2022,1/1/2023,\r
2,GRANITE PEAK CORP,Alpine skiing facilities witho,140,138173,1,0,3,0,9,20,...,0,0,0,0,914144,1,3,2022,1/1/2023,\r
3,"Dragon Industrial Wrap, LLC",Tank lining contractors,11,22880,2,0,0,0,0,0,...,0,0,0,0,914157,1,1,2022,1/1/2023,\r
4,Kristi's test company 2/24/21,Antique auto dealers,12000,12000,1,1,1,1,1,1,...,0,1,1,0,693829,1,2,2022,1/1/2023,\r
5,Cobb South 298,"Furniture moving, used",20,30800,2,0,0,0,0,0,...,0,0,0,0,155645,1,2,2022,1/1/2023,\r
6,Diamond S Mobile Welding LLC,Welding,1,2400,2,0,0,0,0,0,...,0,0,0,0,905945,1,1,2022,1/1/2023,\r
7,T&J Industries Development and,utility contractors,1260,91200,2,0,0,0,0,0,...,0,0,0,0,812418,1,2,2022,1/1/2023,\r
8,Divine Power LLC,Power Line,30,76000,2,0,0,0,0,0,...,0,0,0,0,913636,1,2,2022,1/1/2023,\r
9,Vac2Go,Vacuum Truck Rental & Service,4,8320,2,0,0,0,0,0,...,0,0,0,0,914148,1,1,2022,1/1/2023,\r

In [4]:
%%sql
CREATE TABLE training_data_clean AS
SELECT 
    my_row_id,
    company_name,
    industry_description,
    NULLIF(annual_average_employees, '') AS annual_average_employees,
    NULLIF(total_hours_worked, '')       AS total_hours_worked,
    NULLIF(no_injuries_illnesses, '')    AS no_injuries_illnesses,
    NULLIF(total_deaths, '')             AS total_deaths,
    NULLIF(total_dafw_cases, '')         AS total_dafw_cases,
    NULLIF(total_djtr_cases, '')         AS total_djtr_cases,
    NULLIF(total_other_cases, '')        AS total_other_cases,
    NULLIF(total_dafw_days, '')          AS total_dafw_days,
    NULLIF(total_djtr_days, '')          AS total_djtr_days,
    NULLIF(total_injuries, '')           AS total_injuries,
    NULLIF(total_poisonings, '')         AS total_poisonings,
    NULLIF(total_respiratory_conditions, '') AS total_respiratory_conditions,
    NULLIF(total_skin_disorders, '')     AS total_skin_disorders,
    NULLIF(total_hearing_loss, '')       AS total_hearing_loss,
    NULLIF(total_other_illnesses, '')    AS total_other_illnesses,
    establishment_id,
    establishment_type,
    `size`,
    year_filing_for,
    STR_TO_DATE(created_timestamp, '%m/%d/%Y') AS created_timestamp_dt,
    change_reason
FROM train_data
WHERE year_filing_for REGEXP '^[0-9]{4}$';   -- basic quality filter - valid 4-digit year

Running query in 'mysql+mysqlconnector://ivan:***@localhost:3306'

345573 rows affected.

++
||
++
++

In [5]:
%%sql
SELECT 'industry_description' AS column_name, 
       COUNT(DISTINCT industry_description) AS cardinality 
FROM train_data
UNION ALL
SELECT 'annual_average_employees', COUNT(DISTINCT annual_average_employees) FROM train_data
UNION ALL
SELECT 'total_hours_worked',       COUNT(DISTINCT total_hours_worked) FROM train_data
UNION ALL
SELECT 'no_injuries_illnesses',    COUNT(DISTINCT no_injuries_illnesses) FROM train_data
UNION ALL
SELECT 'total_deaths',             COUNT(DISTINCT total_deaths) FROM train_data
UNION ALL
SELECT 'total_dafw_cases',         COUNT(DISTINCT total_dafw_cases) FROM train_data
UNION ALL
SELECT 'total_djtr_cases',         COUNT(DISTINCT total_djtr_cases) FROM train_data
UNION ALL
SELECT 'total_other_cases',        COUNT(DISTINCT total_other_cases) FROM train_data
UNION ALL
SELECT 'total_dafw_days',          COUNT(DISTINCT total_dafw_days) FROM train_data
UNION ALL
SELECT 'total_djtr_days',          COUNT(DISTINCT total_djtr_days) FROM train_data
UNION ALL
SELECT 'total_injuries',           COUNT(DISTINCT total_injuries) FROM train_data
UNION ALL
SELECT 'total_poisonings',         COUNT(DISTINCT total_poisonings) FROM train_data
UNION ALL
SELECT 'total_respiratory_conditions', COUNT(DISTINCT total_respiratory_conditions) FROM train_data
UNION ALL
SELECT 'total_skin_disorders',     COUNT(DISTINCT total_skin_disorders) FROM train_data
UNION ALL
SELECT 'total_hearing_loss',       COUNT(DISTINCT total_hearing_loss) FROM train_data
UNION ALL
SELECT 'total_other_illnesses',    COUNT(DISTINCT total_other_illnesses) FROM train_data
UNION ALL
SELECT 'establishment_id',         COUNT(DISTINCT establishment_id) FROM train_data
UNION ALL
SELECT 'establishment_type',       COUNT(DISTINCT establishment_type) FROM train_data
UNION ALL
SELECT 'size',                     COUNT(DISTINCT size) FROM train_data
UNION ALL
SELECT 'year_filing_for',          COUNT(DISTINCT year_filing_for) FROM train_data
UNION ALL
SELECT 'created_timestamp',        COUNT(DISTINCT created_timestamp) FROM train_data
UNION ALL
SELECT 'change_reason',            COUNT(DISTINCT change_reason) FROM train_data
ORDER BY column_name;

Running query in 'mysql+mysqlconnector://ivan:***@localhost:3306'

22 rows affected.

                column_name  cardinality
0  annual_average_employees         3347
1             change_reason         2954
2         created_timestamp          257
3          establishment_id       345573
4        establishment_type            5
5      industry_description        12932
6     no_injuries_illnesses            2
7                      size            3
8          total_dafw_cases          334
9           total_dafw_days         2576

In [6]:
%%sql
-- =============================================================
--  Occupational Safety & Health – HeatWave AutoML Preparation
--  Script creates 3 levels of training tables + model training
-- =============================================================
-- =============================================================
-- OPTION 1 – Basic cleaning (maximum traceability, minimal transformation)
-- =============================================================
DROP TABLE IF EXISTS ML_TRAIN_OPTION1;
CREATE TABLE IF NOT EXISTS ML_TRAIN_OPTION1 AS
SELECT 
    my_row_id,
    company_name,
    industry_description,
    establishment_type,
    `size`,
    year_filing_for,
    
    CAST(NULLIF(TRIM(annual_average_employees), '') AS DECIMAL(14,2))     AS annual_average_employees,
    CAST(NULLIF(TRIM(total_hours_worked), '')       AS DECIMAL(18,2))     AS total_hours_worked,
    CAST(NULLIF(TRIM(no_injuries_illnesses), '')    AS UNSIGNED)          AS no_injuries_illnesses,
    CAST(NULLIF(TRIM(total_deaths), '')             AS UNSIGNED)          AS total_deaths,
    CAST(NULLIF(TRIM(total_dafw_cases), '')         AS UNSIGNED)          AS total_dafw_cases,
    CAST(NULLIF(TRIM(total_djtr_cases), '')         AS UNSIGNED)          AS total_djtr_cases,
    CAST(NULLIF(TRIM(total_other_cases), '')        AS UNSIGNED)          AS total_other_cases,
    CAST(NULLIF(TRIM(total_dafw_days), '')          AS UNSIGNED)          AS total_dafw_days,
    CAST(NULLIF(TRIM(total_djtr_days), '')          AS UNSIGNED)          AS total_djtr_days,
    CAST(NULLIF(TRIM(total_injuries), '')           AS UNSIGNED)          AS total_injuries,
    CAST(NULLIF(TRIM(total_poisonings), '')         AS UNSIGNED)          AS total_poisonings,
    CAST(NULLIF(TRIM(total_respiratory_conditions), '') AS UNSIGNED)      AS total_respiratory_conditions,
    CAST(NULLIF(TRIM(total_skin_disorders), '')     AS UNSIGNED)          AS total_skin_disorders,
    CAST(NULLIF(TRIM(total_hearing_loss), '')       AS UNSIGNED)          AS total_hearing_loss,
    CAST(NULLIF(TRIM(total_other_illnesses), '')    AS UNSIGNED)          AS total_other_illnesses,
    
    establishment_id,
    created_timestamp,
    change_reason
FROM train_data
WHERE year_filing_for REGEXP '^[0-9]{4}$'
  AND NULLIF(TRIM(total_hours_worked), '') IS NOT NULL;

Running query in 'mysql+mysqlconnector://ivan:***@localhost:3306'

345572 rows affected.

++
||
++
++

In [7]:
%%sql

select @mymodel =  'demo_injuries_ml';

DELETE from ML_SCHEMA_ivan.MODEL_CATALOG where model_handle = @mymodel;

CALL sys.ML_TRAIN(
    'demodata.ML_TRAIN_OPTION1',
    'total_injuries',                          
    JSON_OBJECT(
        'task', 'regression',
        'optimization_metric', 'neg_mean_squared_error',
        'exclude_column_list', JSON_ARRAY('my_row_id', 'created_timestamp')
    ),
    @mymodel
);

Running query in 'mysql+mysqlconnector://ivan:***@localhost:3306'

1 rows affected.

++
||
++
++

In [9]:
%%sql
SELECT * from ML_SCHEMA_ivan.MODEL_CATALOG where model_handle = @mymodel;

Running query in 'mysql+mysqlconnector://ivan:***@localhost:3306'

1 rows affected.

+----------+----------------------------------------------+------------------+------------+--------------+-------------+-----------------+--------------------+---------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------+-------------------+-------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| model_id |                 model_handle                 |    model_type    |    task    | model_object | model_owner | build_timestamp | target_column_name |      train_table_name     |                                                                                                                                                                                                                       column_names                                                                                                                                                                                                                      |                                                                                                                                                                                                                                                                                   model_explanation                                                                                                                                                                                                                                                                                   | last_accessed | model_object_size | notes |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        model_metadata                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
+----------+----------------------------------------------+------------------+------------+--------------+-------------+-----------------+--------------------+---------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------+-------------------+-------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|    10    | demodata.ML_TRAIN_OPTION1_ivan_1769129767964 | LinearRegression | regression |     None     |     ivan    |    1769129816   |   total_injuries   | demodata.ML_TRAIN_OPTION1 | ['company_name', 'industry_description', 'establishment_type', 'size', 'year_filing_for', 'annual_average_employees', 'total_hours_worked', 'no_injuries_illnesses', 'total_deaths', 'total_dafw_cases', 'total_djtr_cases', 'total_other_cases', 'total_dafw_days', 'total_djtr_days', 'total_poisonings', 'total_respiratory_conditions', 'total_skin_disorders', 'total_hearing_loss', 'total_other_illnesses', 'establishment_id', 'change_reason'] | {"permutation_importance": {"size": 0, "company_name": 0, "total_deaths": 0, "change_reason": 0, "total_dafw_days": 0, "total_djtr_days": 0, "year_filing_for": 0, "establishment_id": 0, "total_dafw_cases": 0.8113, "total_djtr_cases": 0.4309, "total_poisonings": 0, "total_other_cases": 0.4041, "establishment_type": 0, "total_hearing_loss": 0.0022, "total_hours_worked": 0, "industry_description": 0, "total_skin_disorders": 0.0004, "no_injuries_illnesses": 0, "total_other_illnesses": 0.1208, "annual_average_employees": 0, "total_respiratory_conditions": 0.4431}} |      None     |      8441910      |  None | {"task": "regression", "notes": null, "chunks": 1, "format": "HWMLv2.0", "n_rows": 345572, "status": "Ready", "options": {"task": "regression", "model_explainer": "permutation_importance", "exclude_column_list": ["my_row_id", "created_timestamp"], "optimization_metric": "neg_mean_squared_error", "prediction_explainer": "permutation_importance"}, "n_columns": 21, "column_names": ["company_name", "industry_description", "establishment_type", "size", "year_filing_for", "annual_average_employees", "total_hours_worked", "no_injuries_illnesses", "total_deaths", "total_dafw_cases", "total_djtr_cases", "total_other_cases", "total_dafw_days", "total_djtr_days", "total_poisonings", "total_respiratory_conditions", "total_skin_disorders", "total_hearing_loss", "total_other_illnesses", "establishment_id", "change_reason"], "contamination": null, "model_quality": "high", "training_time": 35.63807678222656, "algorithm_name": "LinearRegression", "training_score": null, "build_timestamp": 1769129816, "hyperparameters": {"copy_X": true, "n_jobs": 8, "positive": false, "fit_intercept": true}, "n_selected_rows": 166275, "training_params": {"recommend": "ratings", "force_use_X": false, "recommend_k": 3, "remove_seen": true, "ranking_topk": 10, "lsa_components": 100, "ranking_threshold": 1, "feedback_threshold": 1}, "train_table_name": "demodata.ML_TRAIN_OPTION1", "model_explanation": {"permutation_importance": {"size": 0, "company_name": 0, "total_deaths": 0, "change_reason": 0, "total_dafw_days": 0, "total_djtr_days": 0, "year_filing_for": 0, "establishment_id": 0, "total_dafw_cases": 0.8113, "total_djtr_cases": 0.4309, "total_poisonings": 0, "total_other_cases": 0.4041, "establishment_type": 0, "total_hearing_loss": 0.0022, "total_hours_worked": 0, "industry_description": 0, "total_skin_disorders": 0.0004, "no_injuries_illnesses": 0, "total_other_illnesses": 0.1208, "annual_average_employees": 0, "total_respiratory_conditions": 0.4431}}, "n_selected_columns": 17, "target_column_name": "total_injuries", "optimization_metric": "neg_mean_squared_error", "selected_column_names": ["annual_average_employees", "change_reason", "establishment_type", "industry_description", "no_injuries_illnesses", "size", "total_dafw_cases", "total_dafw_days", "total_deaths", "total_djtr_cases", "total_hearing_loss", "total_hours_worked", "total_other_cases", "total_other_illnesses", "total_poisonings", "total_respiratory_conditions", "total_skin_disorders"], "training_drift_metric": {"mean": 0.3992, "variance": 871.6891}} |
+----------+----------------------------------------------+------------------+------------+--------------+-------------+-----------------+--------------------+---------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------+-------------------+-------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

In [10]:
%%sql

-- =============================================================================
-- OPTION 2 – Enriched version (recommended)
-- =============================================================================
DROP TABLE IF EXISTS ML_TRAIN_OPTION2;

CREATE TABLE IF NOT EXISTS ML_TRAIN_OPTION2 AS
SELECT 
    industry_description,
    establishment_type,
    `size`,
    year_filing_for,
    
    CAST(NULLIF(TRIM(annual_average_employees), '') AS DECIMAL(14,2))     AS avg_employees,
    CAST(NULLIF(TRIM(total_hours_worked), '')       AS DECIMAL(18,2))     AS total_hours_worked,
    CAST(NULLIF(TRIM(total_deaths), '')             AS UNSIGNED)          AS deaths,
    CAST(NULLIF(TRIM(total_dafw_cases), '')         AS UNSIGNED)          AS dafw_cases,
    CAST(NULLIF(TRIM(total_djtr_cases), '')         AS UNSIGNED)          AS djtr_cases,
    CAST(NULLIF(TRIM(total_other_cases), '')        AS UNSIGNED)          AS other_cases,
    CAST(NULLIF(TRIM(total_dafw_days), '')          AS UNSIGNED)          AS dafw_days,
    CAST(NULLIF(TRIM(total_djtr_days), '')          AS UNSIGNED)          AS djtr_days,
    CAST(NULLIF(TRIM(total_injuries), '')           AS UNSIGNED)          AS total_injuries,
    
    -- Corrected total_illnesses calculation
    COALESCE(CAST(NULLIF(TRIM(total_poisonings), '') AS UNSIGNED), 0) +
    COALESCE(CAST(NULLIF(TRIM(total_respiratory_conditions), '') AS UNSIGNED), 0) +
    COALESCE(CAST(NULLIF(TRIM(total_skin_disorders), '') AS UNSIGNED), 0) +
    COALESCE(CAST(NULLIF(TRIM(total_hearing_loss), '') AS UNSIGNED), 0) +
    COALESCE(CAST(NULLIF(TRIM(total_other_illnesses), '') AS UNSIGNED), 0)   AS total_illnesses,
    
    -- TRIR (Total Recordable Incident Rate)
    CASE 
        WHEN CAST(NULLIF(TRIM(total_hours_worked), '') AS DECIMAL(18,2)) > 0 
        THEN ROUND(
            (CAST(NULLIF(TRIM(total_injuries), '') AS DECIMAL(12,2)) * 200000.0) /
            CAST(NULLIF(TRIM(total_hours_worked), '') AS DECIMAL(18,2)), 2)
        ELSE NULL 
    END AS TRIR,
    
    -- DAFW Rate
    CASE 
        WHEN CAST(NULLIF(TRIM(total_hours_worked), '') AS DECIMAL(18,2)) > 0 
        THEN ROUND(
            (CAST(NULLIF(TRIM(total_dafw_days), '') AS DECIMAL(12,2)) * 200000.0) /
            CAST(NULLIF(TRIM(total_hours_worked), '') AS DECIMAL(18,2)), 2)
        ELSE NULL 
    END AS DAFW_rate,
    
    CASE WHEN CAST(NULLIF(TRIM(total_deaths), '') AS UNSIGNED) > 0 
         THEN 1 ELSE 0 END AS has_fatality,
    
    CASE WHEN CAST(NULLIF(TRIM(total_dafw_days), '') AS UNSIGNED) >= 30 
         THEN 1 ELSE 0 END AS severe_lost_time

FROM train_data
WHERE year_filing_for REGEXP '^[0-9]{4}$'
  AND NULLIF(TRIM(total_hours_worked), '') IS NOT NULL
  AND CAST(NULLIF(TRIM(total_hours_worked), '') AS DECIMAL(18,2)) > 0;

Running query in 'mysql+mysqlconnector://ivan:***@localhost:3306'

344367 rows affected.

++
||
++
++

In [12]:
%%sql
    
SET @model_handle = 'demo_option2_enriched';

DELETE from ML_SCHEMA_ivan.MODEL_CATALOG where model_handle COLLATE utf8mb4_0900_ai_ci= @model_handle;
CALL sys.ML_TRAIN(
    'demodata.ML_TRAIN_OPTION2',
    'TRIR',
    JSON_OBJECT(
        'task', 'regression',
        'optimization_metric', 'neg_mean_squared_error'
    ),
    @model_handle
);

Running query in 'mysql+mysqlconnector://ivan:***@localhost:3306'

++
||
++
++

In [13]:
%%sql
SELECT * from ML_SCHEMA_ivan.MODEL_CATALOG where model_handle = @model_handle;

Running query in 'mysql+mysqlconnector://ivan:***@localhost:3306'

1 rows affected.

+----------+-----------------------+------------------+------------+--------------+-------------+-----------------+--------------------+---------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------+-------------------+-------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| model_id |      model_handle     |    model_type    |    task    | model_object | model_owner | build_timestamp | target_column_name |      train_table_name     |                                                                                                                                      column_names                                                                                                                                     |                                                                                                                                                                               model_explanation                                                                                                                                                                                | last_accessed | model_object_size | notes |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     model_metadata                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
+----------+-----------------------+------------------+------------+--------------+-------------+-----------------+--------------------+---------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------+-------------------+-------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|    11    | demo_option2_enriched | LinearRegression | regression |     None     |     ivan    |    1769129968   |        TRIR        | demodata.ML_TRAIN_OPTION2 | ['industry_description', 'establishment_type', 'size', 'year_filing_for', 'avg_employees', 'total_hours_worked', 'deaths', 'dafw_cases', 'djtr_cases', 'other_cases', 'dafw_days', 'djtr_days', 'total_injuries', 'total_illnesses', 'DAFW_rate', 'has_fatality', 'severe_lost_time'] | {"permutation_importance": {"size": 0, "deaths": 0, "DAFW_rate": 0.5209, "dafw_days": 0, "djtr_days": 0, "dafw_cases": 0, "djtr_cases": 0, "other_cases": 0, "has_fatality": 0, "avg_employees": 0, "total_injuries": 0.0005, "total_illnesses": 0, "year_filing_for": 0, "severe_lost_time": 0, "establishment_type": 0, "total_hours_worked": 0, "industry_description": 0}} |      None     |       929810      |  None | {"task": "regression", "notes": null, "chunks": 1, "format": "HWMLv2.0", "n_rows": 344367, "status": "Ready", "options": {"task": "regression", "model_explainer": "permutation_importance", "optimization_metric": "neg_mean_squared_error", "prediction_explainer": "permutation_importance"}, "n_columns": 17, "column_names": ["industry_description", "establishment_type", "size", "year_filing_for", "avg_employees", "total_hours_worked", "deaths", "dafw_cases", "djtr_cases", "other_cases", "dafw_days", "djtr_days", "total_injuries", "total_illnesses", "DAFW_rate", "has_fatality", "severe_lost_time"], "contamination": null, "model_quality": "high", "training_time": 29.233802795410156, "algorithm_name": "LinearRegression", "training_score": null, "build_timestamp": 1769129968, "hyperparameters": {"copy_X": true, "n_jobs": 8, "positive": false, "fit_intercept": true}, "n_selected_rows": 55899, "training_params": {"recommend": "ratings", "force_use_X": false, "recommend_k": 3, "remove_seen": true, "ranking_topk": 10, "lsa_components": 100, "ranking_threshold": 1, "feedback_threshold": 1}, "train_table_name": "demodata.ML_TRAIN_OPTION2", "model_explanation": {"permutation_importance": {"size": 0, "deaths": 0, "DAFW_rate": 0.5209, "dafw_days": 0, "djtr_days": 0, "dafw_cases": 0, "djtr_cases": 0, "other_cases": 0, "has_fatality": 0, "avg_employees": 0, "total_injuries": 0.0005, "total_illnesses": 0, "year_filing_for": 0, "severe_lost_time": 0, "establishment_type": 0, "total_hours_worked": 0, "industry_description": 0}}, "n_selected_columns": 3, "target_column_name": "TRIR", "optimization_metric": "neg_mean_squared_error", "selected_column_names": ["DAFW_rate", "total_hours_worked", "total_injuries"], "training_drift_metric": {"mean": 0.3195, "variance": 2254.6445}} |
+----------+-----------------------+------------------+------------+--------------+-------------+-----------------+--------------------+---------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------+-------------------+-------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

In [93]:
%%sql

-- =============================================================================
-- OPTION 3 – Minimal & fast version
-- =============================================================================

CREATE TABLE IF NOT EXISTS ML_TRAIN_OPTION3 AS
SELECT 
    industry_description,
    `size`,
    establishment_type,
    year_filing_for,
    
    CAST(NULLIF(TRIM(total_hours_worked), '')   AS DECIMAL(18,2))     AS total_hours_worked,
    CAST(NULLIF(TRIM(total_injuries), '')       AS UNSIGNED)          AS total_injuries,
    CAST(NULLIF(TRIM(total_deaths), '')         AS UNSIGNED)          AS deaths,
    CAST(NULLIF(TRIM(total_dafw_days), '')      AS UNSIGNED)          AS dafw_days,
    
    CASE 
        WHEN CAST(NULLIF(TRIM(total_hours_worked), '') AS DECIMAL(18,2)) > 0 
        THEN ROUND(
            (CAST(NULLIF(TRIM(total_injuries), '') AS DECIMAL(12,2)) * 200000.0) / 
            CAST(NULLIF(TRIM(total_hours_worked), '') AS DECIMAL(18,2)), 2)
        ELSE NULL 
    END AS TRIR_approx

FROM train_data
WHERE year_filing_for REGEXP '^[0-9]{4}$'
  AND total_hours_worked REGEXP '^[0-9.]+$'
  AND total_injuries   REGEXP '^[0-9]+$'
  AND CAST(NULLIF(TRIM(total_hours_worked), '') AS DECIMAL(18,2)) > 0;

Running query in 'mysql+mysqlconnector://admin:***@10.1.1.204:3306/sysmax'

344367 rows affected.

++
||
++
++

In [95]:
%%sql

-- Train model - Option 3 (baseline)
SET @model_handle = 'demo_trip_approx_ml';
CALL sys.ML_TRAIN(
    'demodata.ML_TRAIN_OPTION3',
    'TRIR_approx',
    JSON_OBJECT(
        'task', 'regression',
        'optimization_metric', 'neg_mean_squared_error'
    ),
    @model_handle
);

Running query in 'mysql+mysqlconnector://admin:***@10.1.1.204:3306/sysmax'

++
||
++
++