In [108]:
%load_ext sql
# Heatwave 9.5.x and above
# Please change the ML_SCHEMA_ivan to ML_SCHEMA_{login}
# login should be your user name log in to the DB

%sql show databases;

The sql extension is already loaded. To reload it, use:
  %reload_ext sql

Running query in 'mysql+mysqlconnector://ivan:***@localhost:3306'

20 rows affected.

                     Database
0                LogAnomalyDB
1             ML_SCHEMA_admin
2              ML_SCHEMA_ivan
3           ML_SCHEMA_mieszko
4        ML_SCHEMA_sysmaxdemo
5                   airportdb
6                  creditcard
7                    demodata
8                   financedb
9  fraud_detection_creditcard

In [109]:
%%sql
create database if not exists LogAnomalyDB;
use LogAnomalyDB;

Running query in 'mysql+mysqlconnector://ivan:***@localhost:3306'

1 rows affected.

++
||
++
++

In [110]:
%%sql
select data, logged, error_code from performance_schema.error_log where error_code not in ("MY-010914") order by logged desc  limit 10;

Running query in 'mysql+mysqlconnector://ivan:***@localhost:3306'

10 rows affected.

                                                data  ... error_code
0      Set g_fresh_check_status_json_needed to false  ...  MY-011071
1  check_status_json updated to {"0":"{\"inter_dr...  ...  MY-011071
2     ML Nodes list change detected, gathering info.  ...  MY-011071
3      Set g_fresh_check_status_json_needed to false  ...  MY-011071
4  check_status_json updated to {"0":"{\"inter_dr...  ...  MY-011071
5     ML Nodes list change detected, gathering info.  ...  MY-011071
6      Set g_fresh_check_status_json_needed to false  ...  MY-011071
7  check_status_json updated to {"0":"{\"inter_dr...  ...  MY-011071
8     ML Nodes list change detected, gathering info.  ...  MY-011071
9        Accumulated into hw_data_scanned is 1 in MB  ...  MY-011071

[10 rows x 3 columns]

In [111]:
%%sql
use LogAnomalyDB;

CREATE TABLE if not exists training_data (
    log_id INT AUTO_INCREMENT PRIMARY KEY,
    log_message TEXT,
    timestamp DATETIME,
    target TINYINT
);

Running query in 'mysql+mysqlconnector://ivan:***@localhost:3306'

++
||
++
++

In [112]:
%%sql
use LogAnomalyDB;

CREATE TABLE if not exists training_data (
    log_id INT AUTO_INCREMENT PRIMARY KEY,
    log_message TEXT,
    timestamp DATETIME,
    target TINYINT
);

truncate table training_data;

CREATE TABLE if not exists testing_data (
    log_id INT AUTO_INCREMENT PRIMARY KEY,
    log_message TEXT,
    timestamp DATETIME,
    target TINYINT
);

truncate table testing_data;



INSERT INTO training_data (log_message, timestamp, target) VALUES
    ("User login successful: admin", "2023-08-07 09:00:00", 0),
    ("Database connection established", "2023-08-07 09:05:23", 0),
    ("Failed login attempt from IP: 192.168.1.20", "2023-08-07 09:12:15", 1),
    ("Server load is high: 85%", "2023-08-07 09:20:30", 1),
    ("Aborted connection 654465 to db: 'unconnected' user: 'unauthenticated' host: 'nlb-2025-0331-1249.publicloadbalan.vcnivanmalondon.oraclevcn.com' (Got an error reading communication packets)", "2025-11-11 10:40:19.325877", 0),
    ("TP conn (init: in, queue, auth, err, ok. port: managed(delta), active, opened, closed, added, dropped): Init: 72, 0, 6, 72, 0. Usr: 9(+0), 3, 0, 0, 0, 0. Adm: 4(+0), 3, 0, 0, 0, 0.", "2025-11-11 10:41:50.478543", 0),
    ("Persisted RestorePoint at scn: 1391531", "2025-11-11 10:39:41.933180", 0),
    ("[QKRN] HeatWave Requesting Hypergraph Simplification for MY engine myid=12920996: Stage 1: SG pairs: 532, #plans: 2160, #plans current stage: 2160 :: requested SG pairs: 532, allowed time triggered by: system at 1.8 ms", "2025-11-11 10:39:45.632354", 0), 
    ("Skip STALE table douyu.media from RestorePoint persistence", "2025-02-12 16:31:23.43544", 1),
    ("[TRUNCATE POST-HOOK] Table `xdb`.`temp_query_lookup_table` found in Global State, marking it as stale.", "2025-02-12 17:28:46.588884", 1),
    ("Received EOQ from node #0. Query qid=77697, status OOM", "2025-02-12 16:15:55.359746", 1),
    ("User logout: Jane", "2023-08-07 18:10:00", 0);



INSERT INTO testing_data (log_message, timestamp, target) VALUES
    ("User login failed: Invalid credentials", "2023-08-08 10:30:00", 1),
    ("Unusual network traffic from IP: 10.0.0.5", "2023-08-08 12:45:30", 1);

select * from testing_data;

Running query in 'mysql+mysqlconnector://ivan:***@localhost:3306'

12 rows affected.

2 rows affected.

2 rows affected.

   log_id  ... target
0       1  ...      1
1       2  ...      1

[2 rows x 4 columns]

In [113]:


%%sql  # delete the training model for the log anomaly
delete from ML_SCHEMA_ivan.MODEL_CATALOG where train_table_name = 'LogAnomalyDB.training_data';
select * from ML_SCHEMA_ivan.MODEL_CATALOG where train_table_name = 'LogAnomalyDB.training_data';

Running query in 'mysql+mysqlconnector://ivan:***@localhost:3306'

1 rows affected.

Empty DataFrame
Columns: [model_id, model_handle, model_type, task, model_object, model_owner, build_timestamp, target_column_name, train_table_name, column_names, model_explanation, last_accessed, model_object_size, notes, model_metadata]
Index: []

In [114]:
"""
Unsupervised Anomaly Detection
 When running an unsupervised anomaly detection model, 
 the machine learning algorithm requires no labeled data. 
 When training the model, the target_column_name parameter must be set to NULL.
"""
%sql CALL sys.ML_TRAIN('LogAnomalyDB.training_data',  NULL, JSON_OBJECT('task', 'log_anomaly_detection', 'contamination', 0.05, 'exclude_column_list', JSON_ARRAY('log_id', 'timestamp', 'target')), @unsupervised_log_model);

Running query in 'mysql+mysqlconnector://ivan:***@localhost:3306'

++
||
++
++

In [115]:
%sql CALL sys.ML_MODEL_LOAD(@unsupervised_log_model, NULL);
%sql select @unsupervised_log_model;

Running query in 'mysql+mysqlconnector://ivan:***@localhost:3306'

Running query in 'mysql+mysqlconnector://ivan:***@localhost:3306'

1 rows affected.

  @unsupervised_log_model
0     LogAnomalyDBModel01

In [116]:
%%sql 

CALL sys.ML_SCORE('LogAnomalyDB.testing_data', 'target', @unsupervised_log_model, 'f1', @anomaly_log_score, NULL);
select @anomaly_log_score;

Running query in 'mysql+mysqlconnector://ivan:***@localhost:3306'

1 rows affected.

   @anomaly_log_score
0                   1

In [117]:
%sql drop table if exists LogAnomalyDB.log_predictions_unsupervised;
%sql CALL sys.ML_PREDICT_TABLE('LogAnomalyDB.testing_data', @unsupervised_log_model, 'LogAnomalyDB.log_predictions_unsupervised',JSON_OBJECT('logad_options',JSON_OBJECT('summarize_logs', TRUE)));

Running query in 'mysql+mysqlconnector://ivan:***@localhost:3306'

Running query in 'mysql+mysqlconnector://ivan:***@localhost:3306'

++
||
++
++

In [118]:
%sql select * from LogAnomalyDB.log_predictions_unsupervised;

Running query in 'mysql+mysqlconnector://ivan:***@localhost:3306'

1 rows affected.

   id  ...                                         ml_results
0   1  ...  {"summary": "The user's login attempt was unsu...

[1 rows x 4 columns]

In [119]:

%%sql
-- 9.5.0 keyword_model

SET @unsupervised_log_model = 'LogAnomalyDBModel01';
delete from ML_SCHEMA_ivan.MODEL_CATALOG where train_table_name = 'LogAnomalyDB.training_data';
select * from ML_SCHEMA_ivan.MODEL_CATALOG where train_table_name = 'LogAnomalyDB.training_data';


CALL sys.ML_TRAIN('LogAnomalyDB.training_data', NULL, 
                          JSON_OBJECT('task', 'log_anomaly_detection', 
                                      'exclude_column_list', JSON_ARRAY('log_id', 'timestamp', 'target'),
                                      'contamination', 0.05,
                                      'logad_options', 
                                      JSON_OBJECT('embedding_model', 'all_minilm_l12_v2', 'keyword_model', 'tf-idf')), @unsupervised_log_model);

Running query in 'mysql+mysqlconnector://ivan:***@localhost:3306'

1 rows affected.

++
||
++
++

In [120]:
%%sql

SELECT model_handle, model_type FROM ML_SCHEMA_ivan.MODEL_CATALOG WHERE model_handle=@unsupervised_log_model;

Running query in 'mysql+mysqlconnector://ivan:***@localhost:3306'

1 rows affected.

          model_handle model_type
0  LogAnomalyDBModel01       GKNN

In [121]:
%%sql
# drop the result table first
# and load the model
 drop table if exists LogAnomalyDB.log_predictions_unsupervised;
 CALL sys.ML_MODEL_LOAD(@unsupervised_log_model, NULL);
 CALL sys.ML_PREDICT_TABLE('LogAnomalyDB.testing_data', @unsupervised_log_model, 'LogAnomalyDB.log_predictions_unsupervised', 
                                  JSON_OBJECT('logad_options', JSON_OBJECT('summarize_logs', TRUE)));

Running query in 'mysql+mysqlconnector://ivan:***@localhost:3306'

++
||
++
++

In [122]:
%%sql
# show the prediction result

SELECT * from LogAnomalyDB.log_predictions_unsupervised;

Running query in 'mysql+mysqlconnector://ivan:***@localhost:3306'

1 rows affected.

   id  ...                                         ml_results
0   1  ...  {"summary": "The user's login attempt was unsu...

[1 rows x 4 columns]

In [123]:
%%sql
# The following example enables semi-supervised learning with additional options.
delete from ML_SCHEMA_ivan.MODEL_CATALOG where train_table_name = 'LogAnomalyDB.training_data';
select * from ML_SCHEMA_ivan.MODEL_CATALOG where train_table_name = 'LogAnomalyDB.training_data';
SET @semisupervised_model_options='logAnamaly_model02';
CALL sys.ML_TRAIN('LogAnomalyDB.training_data', "target", 
                          CAST('{"task": "anomaly_detection", "contamination": 0.05,
                                 "exclude_column_list": ["log_id", "timestamp"],
                                 "experimental": {"semisupervised": {"supervised_submodel_options": {"min_labels": 10, "n_neighbors": 3}, 
                                 "ensemble_score": "recall"}}}' as JSON), @semisupervised_model_options);

Running query in 'mysql+mysqlconnector://ivan:***@localhost:3306'

1 rows affected.

++
||
++
++

In [124]:
%%sql

SELECT model_handle, model_type FROM ML_SCHEMA_ivan.MODEL_CATALOG WHERE model_handle=@semisupervised_model_options;

Running query in 'mysql+mysqlconnector://ivan:***@localhost:3306'

1 rows affected.

         model_handle model_type
0  logAnamaly_model02       GKNN

In [125]:
%%sql
 CALL sys.ML_MODEL_LOAD(@semisupervised_model_options, NULL);

Running query in 'mysql+mysqlconnector://ivan:***@localhost:3306'

++
||
++
++

In [126]:
%%sql
 drop table if exists LogAnomalyDB.log_predictions_supervised;
 CALL sys.ML_PREDICT_TABLE('LogAnomalyDB.testing_data', @semisupervised_model_options, 'LogAnomalyDB.log_predictions_supervised', JSON_OBJECT('threshold', 0.55));

Running query in 'mysql+mysqlconnector://ivan:***@localhost:3306'

++
||
++
++

In [127]:
%%sql

select * from LogAnomalyDB.log_predictions_supervised;

Running query in 'mysql+mysqlconnector://ivan:***@localhost:3306'

2 rows affected.

   log_id  ...                                         ml_results
0       1  ...  {"predictions": {"is_anomaly": 1}, "probabilit...
1       2  ...  {"predictions": {"is_anomaly": 0}, "probabilit...

[2 rows x 5 columns]